"""Heuristic music-candidate classifier for YouTube liked videos.

Pure-functional. No I/O. Inputs are the fields surfaced by ``playlistItems``
(title, channel name, description). Output is a small frozen dataclass so
callers can record ``score`` and ``reason`` alongside the boolean verdict
in ``SnapshotItem``.

The classifier is intentionally conservative: positive signals add points,
negative signals subtract. ``is_music_candidate`` flips True when the net
score reaches the positive threshold AND there's at least one positive
signal. This keeps "How I built a synth - vlog" out of the music bucket
even though "synth" is musical.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Each entry is (regex, weight, label). Regexes are compiled IGNORECASE.
_POSITIVE_SIGNALS: tuple[tuple[str, int, str], ...] = (
    (r"\bofficial\s+music\s+video\b", 3, "official music video"),
    (r"\bofficial\s+mv\b", 3, "official mv"),
    (r"\bofficial\s+audio\b", 3, "official audio"),
    (r"\bofficial\s+video\b", 2, "official video"),
    (r"\blyric\s+video\b", 2, "lyric video"),
    (r"\blyrics\b", 2, "lyrics"),
    (r"\bvisualizer\b", 2, "visualizer"),
    (r"\bm/v\b", 2, "m/v"),
    (r"\bmv\b", 1, "mv"),
    (r"\baudio\b", 1, "audio"),
)

# A "channel name ends with - Topic" is a strong signal: YouTube's autogenerated
# music channels are named "<Artist> - Topic".
_CHANNEL_TOPIC_RE = re.compile(r"\s-\s*topic\s*$", re.IGNORECASE)

# "Artist - Title" pattern in title (with at least one space on each side of the dash).
# Conservative: requires the dash to be surrounded by spaces, not embedded in a word.
_ARTIST_DASH_TITLE_RE = re.compile(r"^[^-\n]{2,}\s+-\s+[^-\n]{2,}$")

# Description boilerplate that YouTube's auto-generated music videos always include.
_DESCRIPTION_PROVIDED_RE = re.compile(r"provided to youtube by", re.IGNORECASE)

# Strong negative signals that override most positive signals.
_NEGATIVE_SIGNALS: tuple[tuple[str, int, str], ...] = (
    (r"\bvlog\b", 3, "vlog"),
    (r"\btutorial\b", 3, "tutorial"),
    (r"\bhow\s+to\b", 2, "how-to"),
    (r"\breview\b", 2, "review"),
    (r"\breaction\b", 3, "reaction"),
    (r"\bgameplay\b", 3, "gameplay"),
    (r"\bwalkthrough\b", 2, "walkthrough"),
    (r"\bnews\b", 2, "news"),
    (r"\bshorts?\b", 2, "shorts"),
    (r"\bunboxing\b", 2, "unboxing"),
    (r"\binterview\b", 2, "interview"),
)

# Net score must reach this to flip the boolean True.
_POSITIVE_THRESHOLD = 2


@dataclass(frozen=True)
class Classification:
    is_music_candidate: bool
    score: int
    reason: str


def _scan(text: str, signals: tuple[tuple[str, int, str], ...]) -> tuple[int, list[str]]:
    """Return (total_weight, matched_labels) for ``signals`` against ``text``."""
    total = 0
    labels: list[str] = []
    for pattern, weight, label in signals:
        if re.search(pattern, text, flags=re.IGNORECASE):
            total += weight
            labels.append(label)
    return total, labels


def classify(
    title: str,
    channel: str | None = None,
    description: str | None = None,
) -> Classification:
    """Score a YouTube video as a music candidate or not."""
    title = title or ""
    channel = channel or ""
    description = description or ""

    pos_score, pos_labels = _scan(title, _POSITIVE_SIGNALS)
    neg_score, neg_labels = _scan(title, _NEGATIVE_SIGNALS)
    # Negative signals also scan the channel name and description body.
    extra_neg, extra_neg_labels = _scan(channel + " " + description, _NEGATIVE_SIGNALS)
    neg_score += extra_neg
    neg_labels.extend(extra_neg_labels)

    extra_labels: list[str] = []
    if _CHANNEL_TOPIC_RE.search(channel):
        pos_score += 3
        extra_labels.append("topic channel")
    if _ARTIST_DASH_TITLE_RE.search(title):
        # +2 (one notch above threshold) so an "Artist - Title" titled video
        # on its own clears the music bar even when no other signal fires.
        # This is intentionally stronger than the +1 from a stray "audio"
        # or "mv" token because the dash-pattern is what actual music-channel
        # uploads look like ("The Beatles - Hey Jude").
        pos_score += 2
        extra_labels.append("artist - title")
    if _DESCRIPTION_PROVIDED_RE.search(description):
        pos_score += 3
        extra_labels.append("provided to youtube by")

    score = pos_score - neg_score
    reasons: list[str] = []
    if pos_labels or extra_labels:
        reasons.append("positive: " + ", ".join(pos_labels + extra_labels))
    if neg_labels:
        reasons.append("negative: " + ", ".join(neg_labels))

    is_music = (
        score >= _POSITIVE_THRESHOLD and bool(pos_labels or extra_labels) and not (neg_score >= 3)
    )
    reason = " | ".join(reasons) if reasons else "no signals"
    return Classification(is_music_candidate=is_music, score=score, reason=reason)
